# These are supported funding model platforms

patreon: auvipy
open_collective: celery
ko_fi: # Replace with a single Ko-fi username
tidelift: "pypi/kombu"
custom: # Replace with a single custom sponsorship URL
