version = 1

test_patterns = ["t/**"]

exclude_patterns = [
    "requirements/",
    "extra/**",
    "examples/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"